config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get '/search', to: 'professional#index'
  get '/about', to: 'pages#about'
    get '/searchtest', to: 'pages#searchtest'
      get '/profile', to: 'pages#profile'
        get '/myagents', to: 'pages#myagents'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :saveds
  resources :user do
    resources :professional
    resources :saveds, only: [:index, :destroy]

    resources :specialty
    resources :category
  end

  resources :professional do # empty routes
    resources :saveds, only: [:create, :destroy]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:name]

  has_many :specialties, dependent: :destroy
end

app/models/professional.rb
class Professional < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:specialty_id, :languages]
  belongs_to :user
  belongs_to :specialty
  has_many :saveds
  validates :user_id, presence: true

  accepts_nested_attributes_for :specialty



end

app/models/saved.rb
class Saved < ActiveRecord::Base
  belongs_to :user
  belongs_to :professional
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:name, :category_id]

  belongs_to :category
  has_many :professionals, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :picture, PictureUploader

  include PgSearch
  multisearchable against: [:city]

  has_one :professional, dependent: :destroy

  has_many :saveds, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :hide_footer, if: :devise_controller?

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

  private

  def hide_footer
    @hide_footer = true
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
    @users = User.all
    @categories = Category.all
    @specialties = Specialty.all
    @professionals = Professional.all
  end

  def about
  end

  def contact
  end

  def searchtest
  end

  def profile
  end

  def myagents
  end

  def about
  end


end

app/controllers/professional_controller.rb
class ProfessionalController < ApplicationController
  before_action :find_prof, only: [:show, :edit, :update, :destroy]

  def index
    @professionals = []
    specialty = Specialty.find_by_name(params[:specialty])
    results = PgSearch.multisearch(specialty.id, params[:city], params[:languages])
    results.each do |result|
      @professionals << result.searchable if result.searchable.class == Professional
    end
  end

  def new
    @categories = Category.all
    @specialties = Specialty.all

    @professional = Professional.new
    @professional.build_specialty
  end

  def create
    @categories = Category.all
    @specialties = Specialty.all

    @user = current_user
    professional = @user.build_professional(prof_params)

    if professional.save
      redirect_to user_professional_path(@user.id, professional.id)
    else
      redirect_to user_path
    end
  end

  def edit
  end

  def update
    @professional.update_attributes(prof_params)

    if @professional.save
      redirect_to user_professional_path(@user.id, @professional.id)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @professional.destroy
    redirect_to user_path
  end

  private

  def find_prof
    @user = current_user
    @professional = Professional.find(params[:id])
  end

  def prof_params
    params.require(:professional).permit( :user_id,
      :specialty_id,
      :description,
      :languages,
      :address,
      :phone,
      :prof_email,
      :recommended_by
      )
  end

end

app/controllers/saveds_controller.rb
class SavedsController < ApplicationController
  before_action :set_saved, only: [:destroy]

  def index
    @saveds = current_user.saveds
  end

  def show

  end

  def create
    current_user.saveds.where(professional_id: params[:professional_id]).first_or_create!
    redirect_to user_saveds_path(current_user)
  end

  def destroy
    #current_user.saveds.where(professional_id: params[:professional_id]).destroy
    @saved.destroy
    redirect_to user_saveds_path(current_user)
  end

private

def set_saved
  @saved = Saved.find(params[:id])
end

def saved_param
  params.require(:saved).permit(:user_id, :professional_id)
end

end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  def index
    @specialties = Specialty.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update_attributes(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to welcome_path
  end

  private

  def find_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :picture, :picture_cache, :city)
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :city
    devise_parameter_sanitizer.for(:sign_up) << :picture
    devise_parameter_sanitizer.for(:sign_up) << :picture_cache
  end

  def after_sign_up_path_for(user)
    user_path(user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professional_helper.rb
module ProfessionalHelper
end

app/helpers/saved_helper.rb
module SavedHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/professional/_form.html.erb
<div class="form-box">
  <%= simple_form_for(professional, :url => user_professional_index_path) do |f| %>

    <div class="form-group select required professional_category">
      <label class="select required control-label" for="category">
        <abbr title="required">*</abbr> Profession
      </label>
      <select class='form-control' name="category_id" id="category">
        <%= options_for_select(["Select your profession"]) %>
        <% @categories.each do |category| %>
          <%= options_for_select([category.name]) %>
        <% end %>
      </select>
    </div>

    <div class="form-group select required professional_specialty">
      <label class="select required control-label" for="professional_specialty_id">
        <abbr title="required">*</abbr> Specialty
      </label>
      <select class='form-control' name="professional[specialty_id]" id="professional_specialty_id">
        <%= options_for_select(["Select your specialisation"]) %>
        <% @specialties.uniq.each do |specialty| %>
          <%= options_for_select([[specialty.name, specialty.id, { class: "specialty #{specialty.category.name}" }]]) %>
        <% end %>
      </select>
    </div>

    <%= f.input :description, placeholder: "Provide a short description of your services and experience", required: true %>
    <%= f.input :languages, collection: [ "English", "French", "Dutch", "German"], prompt: "Select your spoken language(s)", required: true %>
    <%= f.input :address, placeholder: "Avenue Louise 6, 1000", required: true %>
    <%= f.input :phone, placeholder: "02 217 83 45", required: true %>
    <%= f.input :prof_email, label: "Professional email", placeholder: "max@maxco.com", required: true %>
    <%= f.input :recommended_by, :as => :hidden, :input_html => { :value => 0 } %>
    <%= f.button :submit, "Create profile" %>
  <% end %>
</div>

app/views/professional/edit.html.erb
<div class="container" style="margin-top: 85px">

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <h1>Edit your professional profile</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <%= render "form", professional: @profesional %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <p><%= link_to "Delete", user_professional_path(@professional), method: :delete %> | <%= link_to "Back", root_path %></p>
    </div>
  </div>
</div>

app/views/professional/index.html.erb
<div class="page-header">
  <h1 class="wordof-color text-center padding">Our trusted professionals</h1>
</div>
<div class="container">
  <div class="row active-with-click">
    <% @professionals.each do |professional| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <article class="material-card Blue">
        <h2>
          <span><%= professional.user.name %></span>
          <strong>
            <% if user_signed_in? %>
            <%= professional.recommended_by %> <%= link_to professional_saveds_path(professional), method: :post do %>
            <i class="fa fa-bookmark"></i>
            <% end %>
            <% end %>
          </strong>
        </h2>
        <div class="mc-content">
          <div class="img-container">
            <%= image_tag professional.user.picture , width: "400", height: "400" %>
          </div>
          <div class="mc-description">
            <%= professional.description %>
          </div>
        </div>
        <a class="mc-btn-action">
          <i class="fa fa-bars"></i>
        </a>
        <div class="mc-footer">
          <a class="fa fa-fw fa-mobile" href="tel:<%= professional.phone %> "></a>
          <a class="fa fa-fw fa-envelope" href="mailto:<%= professional.prof_email %>"></a>
          <a class="fa fa-fw fa-map-marker" href=""></a>
          <%= link_to '', professional_path(professional), class: "fa fa-fw fa-info" %>
        </div>
      </article>
    </div>
    <% end %>
  </div>
</div>

<script src="javascript.js"></script>

app/views/professional/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <h1>Create your profile as a service provider</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <%= render "form", professional: @professional %>
    </div>
  </div>
</div>

app/views/professional/show.html.erb
<!--   <div class="container"> -->
<div class="myprofile margin-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="profilebanner text-center">
          <h3><span class="username"><%= @professional.user.name %></span></h3>
          <br>
          <h3><span class="job"><%= @professional.specialty.category.name %></span></h3>
        </div>
      </div>
    </div>

    <div class="profilecard">
      <%= image_tag @professional.user.picture , width: "400", height: "400" %>

      <div class="descriptionprofile profiledesc">
        <h2> <i class="fa fa-info"></i> Description</h2>
        <p style='padding:20px'><%= @professional.description %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-plus"></i> Specialisations</h2>
          <p><%= @professional.specialty.name %></p>
        </div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-language"></i> Spoken Languages</h2>
          <p><%= @professional.languages%></p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-map-marker"></i> Address</h2>
          <p><%= @professional.address%></p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-mobile"></i> Phone</h2>
          <p><%= @professional.phone%></p>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-envelope"></i> Mail</h2>
          <p><%= @professional.prof_email%></p>
        </div>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="profilebanner">
          <h2> <i class="fa fa-globe"></i> Map</h2>
        </div>
        <div class='myagentsmap'>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2519.738315385742!2d4.358259915455894!3d50.836010879530384!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c3c4888ce3b8b5%3A0xc67fef6c3109b5f1!2sRue+de+Stassart+60%2C+1050+Ixelles%2C+B%C3%A9lgica!5e0!3m2!1ses!2sbe!4v1460448612745" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-offset-2 col-sm-8">
        <p><%= link_to "Back to search", root_path %></p>
    </div>

  </div>
</div>

<script src="javascript.js"></script>

app/views/saveds/index.html.erb
<div class="page-header">
  <h1 class="wordof-color text-center padding">My trusted professionnals</h1>
</div>
<div class="container">

  <div class="row active-with-click">
    <% @saveds.each do |saved| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <article class="material-card Blue">
        <h2>
          <span><%= saved.professional.user.name %></span>
          <strong>

           <% if user_signed_in? %>
           <%= link_to saved, method: :delete, data: {confirm: 'are you sure ?'} do %>
           <i class="fa fa-bookmark"></i>
           <% end %>
           <% end %>
           <%= saved.professional.specialty.category.name %> - <%= saved.professional.specialty.name %>
         </strong>

       </h2>
       <div class="mc-content">
        <div class="img-container">
          <%= image_tag(saved.professional.user.picture, style:"width:400px;height:auto") %>

        </div>
        <div class="mc-description">
          <%= saved.professional.description %>
        </div>
      </div>
      <a class="mc-btn-action">
        <i class="fa fa-bars"></i>
      </a>
      <div class="mc-footer">
        <a class="fa fa-fw fa-mobile" href="tel:<%= saved.professional.phone %> "></a>
        <a class="fa fa-fw fa-envelope" href="mailto:<%= saved.professional.prof_email %>"></a>
        <a class="fa fa-fw fa-map-marker" href=""></a>
        <%= link_to '', professional_path(saved.professional), class: "fa fa-fw fa-info" %>

      </div>
    </article>
  </div>
  <% end %>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12" style="text-align: center;">
    <p><%= link_to "Go to homepage", root_path %></p>
  </div>
</div>
</div>

<script src="javascript.js"></script>

app/views/saveds/show.html.erb
<h1>Saved#show</h1>
<p>Find me in app/views/saved/show.html.erb</p>

app/views/specialties/index.html.erb
<h1>Specialties#index</h1>
<p>Find me in app/views/specialties/index.html.erb</p>

app/views/user/edit.html.erb
<div class="container" style="margin-top: 85px">

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <h1>Edit your user profile</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <div class="form-box">
        <%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
          <%= f.input :name, placeholder: @user.name, required: true %>
          <%= f.input :city, collection: [ "Brussels", "Antwerp", "Ghent", "Paris"], prompt: "Select your city" %>
          <%= f.input :picture, placeholder: @user.picture, required: true %>
          <%= f.input :picture_cache, as: :hidden %>
          <%= f.button :submit, "Update details" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-10">
    <p>Would you like to be listed as a service provider yourself? Create a <%= link_to "professional profile", new_user_professional_path(current_user) %> in just 5 minutes.</p>
  </div>
</div>

app/views/user/show.html.erb
<% @hide_footer = true %>
<div class="container" style="margin-top: 35px">

  <div class="row" style='margin-top: 20px'>
    <div class="col-xs-12 col-sm-12" style="text-align: center;">
      <h1>Hey there!</h1>
      <h3>What do you want to do next?</h3>
    </div>
  </div>

  <div class="container" style="margin-top: 35px">
    <div class="row">

      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <div class="topcrd search">
            <p>Ready to find trusted service providers?</p>
          </div>
          <div class="bottomcrd">
            <h3><%= link_to "Go to search", root_path, id: 'textcrd' %></h3>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <div class="topcrd user">
            <p>Tell us a bit more about yourself?</p>
          </div>
          <div class="bottomcrd">
            <h3><%= link_to "Edit your user profile", edit_user_path(@user), id: 'textcrd' %></h3>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <div class="topcrd professional">
            <p>Get listed as a service provider?</p>
          </div>
          <div class="bottomcrd">
            <h3><%= link_to "Create professional profile", new_user_professional_path(@current_user), id: 'textcrd' %></h3>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-12" style="text-align: center;">
      <p><%= link_to "Delete profile", user_path(@user), method: :delete %> | <%= link_to "Go to homepage", root_path %></p>
    </div>
  </div>
</div>